hr_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from news.views import news_feed
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('booking/', include('booking.urls')),
    path('profiles/', include('profiles.urls')),
    path('scheduling/', include('scheduling.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('contact/', TemplateView.as_view(template_name="contact.html"), name="contact"),
    path('services/', TemplateView.as_view(template_name="services.html"), name="services"),
    path('aboutus/', TemplateView.as_view(template_name="aboutus.html"), name="aboutus"),
    path('news/', include('news.urls', namespace='news')),
    path('summernote/', include('django_summernote.urls')),
    path('login/', LoginView.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import news_feed, like_post, add_comment

app_name = 'news'

urlpatterns = [
    path('', news_feed, name='news_feed'),
    path('like/<int:post_id>/', like_post, name='like_post'),
    path('comment/<int:post_id>/', add_comment, name='add_comment'),
]

scheduling/urls.py
from django.urls import path
from . import views
from booking.views import book_pass

app_name = 'scheduling'

urlpatterns = [
    path('list/', views.workshift_list, name='workshift_list'),
    path('book/', views.book_workshift, name='book_workshift'),
    path('book/<int:workshift_id>/', views.book_workshift, name='book_workshift'),
    path('book-pass/<int:workshift_id>/', book_pass, name='book_pass'),
    path('work-shifts/', views.work_shifts, name='work_shifts'),
    path('work-shifts/add-event/', views.add_event, name='add_event'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('calendar2/', views.calendar_view, name='calendar2'),
    path('employees_calendar/', views.employees_calendar_view, name='employees_calendar'),
    path('cancel/<int:workshift_id>/', views.cancel_workshift, name='cancel_workshift'),
]

scheduling/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings

class WorkShift(models.Model):
    event = models.CharField(max_length=100, default='Event')
    location = models.CharField(max_length=100, default='Location')
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    role = models.CharField(max_length=100, blank=True)
    is_booked = models.BooleanField(default=False)

    def get_current_time(self):
        return timezone.now()
    def __str__(self):
        return self.event
    
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    workshift = models.ForeignKey(WorkShift, on_delete=models.CASCADE)

    def __str__(self):
        return f"Booking: {self.user} - {self.workshift}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.user.profile.booked_workshifts.add(self.workshift)
        self.user.profile.save()

        send_email_notification(self.workshift, self.user)

@login_required
def workshift_list(request):
    from .models import WorkShift
    workshifts = WorkShift.objects.exclude(booking__isnull=False)
    return render(request, 'scheduling/workshift_list.html', {'workshifts': workshifts})

@login_required
def book_workshift(request, workshift_id):
    workshift = get_object_or_404(WorkShift, id=workshift_id)

    if workshift.start_time > timezone.now():
        if request.method == 'POST':
            # Handle the booking logic
            # ...

            # Update the user's profile with the booked workshift
            user_profile = request.user.profile
            user_profile.booked_workshifts.add(workshift)
            user_profile.save()

            # Render a success message
            success_message = 'Du är bokad på detta pass.'
            return render(request, 'scheduling/book_workshift.html', {'workshift': workshift, 'success_message': success_message})

        return render(request, 'scheduling/book_workshift.html', {'workshift': workshift})
    else:
        error_message = 'Detta pass har redan passerat och kan inte bokas.'
        return render(request, 'scheduling/book_workshift.html', {'workshift': workshift, 'error_message': error_message})


@login_required
def work_shifts(request):
    from booking.models import Booking
    user_profile = request.user.profile
    booked_workshifts = Booking.objects.filter(user=user_profile)
    return render(request, 'scheduling/work_shifts.html', {'booked_workshifts': booked_workshifts})

@login_required
def add_event(request):
    # Handle adding event logic
    return render(request, 'scheduling/add_event.html')


def send_email_notification(workshift, user):
    subject = 'Shift Booking Confirmation'
    message = f'You have been booked for the "{workshift}" shift.'
    recipient_list = [user.email]
    html_message = render_to_string('scheduling/email_template.html', {'workshift': workshift})

    send_mail(subject, message, from_email=None, recipient_list=recipient_list, html_message=html_message)

scheduling/forms.py
from django import forms

class EventForm(forms.Form):
    title = forms.CharField(max_length=100)
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()

scheduling/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import WorkShift
from profiles.models import Profile
from .forms import EventForm
from booking.models import Booking
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from .models import Booking


@login_required
def workshift_list(request):
    user_profile = request.user.profile
    now = timezone.now()
    booked_workshifts = user_profile.booked_workshifts.filter(start_time__gt=now)
    return render(request, 'scheduling/workshift_list.html', {'booked_workshifts': booked_workshifts})


@login_required
def book_workshift(request):
    workshifts = WorkShift.objects.filter(is_booked=False)

    if request.method == 'POST':
        # Handle the booking logic
        # ...

        # Check if the selected workshift is already booked
        selected_workshift_id = request.POST.get('workshift_id')
        selected_workshift = get_object_or_404(WorkShift, id=selected_workshift_id)
        if selected_workshift.is_booked:
            messages.error(request, 'This workshift has already been booked.')
            return redirect('scheduling:book_workshift')

        # Check if the workshift has already passed
        current_datetime = timezone.now()
        if selected_workshift.start_time < timezone.now():
            error_message = 'This workshift has already passed and cannot be booked.'
            return render(request, 'scheduling/book_workshift.html', {'workshifts': workshifts, 'error_message': error_message})

        # Create a new booking object
        booking = Booking.objects.create(user=request.user, workshift=selected_workshift)

        # Update the user's profile with the booked workshift
        user_profile = request.user.profile
        user_profile.booked_workshifts.add(selected_workshift)
        user_profile.save()

        # Update the availability of the workshift
        selected_workshift.is_booked = True
        selected_workshift.save()

        # Render the email template
        email_template = send_email_notification(selected_workshift, request.user)

        # Render a success message
        success_message = 'You have successfully booked the workshift.'
        return render(request, 'scheduling/book_workshift.html', {'success_message': success_message, 'email_template': email_template})

    return render(request, 'scheduling/book_workshift.html', {'workshifts': workshifts})




@login_required
def work_shifts(request):
    user_profile = request.user.profile
    now = timezone.now()
    booked_workshifts = user_profile.booked_workshifts.filter(start_time__gt=now)
    worked_workshifts = user_profile.booked_workshifts.filter(start_time__lte=now)
    return render(request, 'scheduling/work_shifts.html', {'booked_workshifts': booked_workshifts, 'worked_workshifts': worked_workshifts})


@login_required
def cancel_workshift(request, workshift_id):
    workshift = get_object_or_404(WorkShift, id=workshift_id)

    if request.method == 'POST':
        # Check if the workshift is already booked
        if not workshift.is_booked:
            messages.error(request, f'{workshift.booked_by.first().user.first_name} {workshift.booked_by.first().user.last_name} wants to cancel the workshift "{workshift.event}".')
            return redirect('scheduling:work_shifts')

        # Get the current user's profile
        user_profile = request.user.profile

        # Check if the user has booked the workshift
        if workshift not in user_profile.booked_workshifts.all():
            messages.error(request, 'You have not booked this workshift.')
            return redirect('scheduling:work_shifts')

        # Remove the workshift from the user's booked workshifts
        user_profile.booked_workshifts.remove(workshift)

        # Update the availability of the workshift
        workshift.is_booked = False
        workshift.save()

        messages.success(request, 'Workshift canceled successfully.')
        return redirect('scheduling:work_shifts')

    # Handle GET request (show confirmation page)
    return render(request, 'scheduling/cancel_workshift.html', {'workshift': workshift})



def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('scheduling:work_shifts')
    else:
        form = EventForm()
    return render(request, 'scheduling/add_event.html', {'form': form})

def calendar_view(request):
    shifts = WorkShift.objects.filter(is_booked=False)
    return render(request, 'scheduling/calendar2.html', {'shifts': shifts})

def employees_calendar_view(request):
    shifts = WorkShift.objects.filter(is_booked=True)
    all_shifts = WorkShift.objects.all()  # or any other query you want to use
    return render(request, 'scheduling/employees_calendar.html', {'shifts': shifts, 'all_shifts': all_shifts})


def send_email_notification(workshift, user):
    subject = 'Workshift Booking Confirmation'
    message = render_to_string('scheduling/email_template.html', {'workshift': workshift})
    recipient_list = [user.email]
    html_message = render_to_string('scheduling/email_template.html', {'workshift': workshift})

    send_mail(subject, message, from_email=None, recipient_list=recipient_list, html_message=html_message)
    pass

scheduling/templates/scheduling/add_event.html
<a href="{% url 'scheduling:add_event' %}">Lägg till pass</a>

scheduling/templates/scheduling/book_workshift.html
{% extends 'dashboard.html' %}
{% load static %}

{% block content %}
<div class="container">
  <h1 class="text-center my-4">Available Workshifts</h1>
  {% if workshifts %}
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th scope="col">Event</th>
            <th scope="col">Start Date</th>
            <th scope="col">Start Time</th>
            <th scope="col">End Time</th>
            <th scope="col">Role</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for workshift in workshifts %}
            {% if workshift.start_time > workshift.get_current_time %}
              <tr>
                <td id="workshift_name_{{ workshift.id }}">{{ workshift.event }}</td>
                <td id="workshift_start_date_{{ workshift.id }}">{{ workshift.start_time|date:"Y-m-d" }}</td>
                <td id="workshift_start_time_{{ workshift.id }}">{{ workshift.start_time|time:"H:i" }}</td>
                <td id="workshift_end_time_{{ workshift.id }}">{{ workshift.end_time|time:"H:i" }}</td>
                <td id="workshift_role_{{ workshift.id }}">{{ workshift.role }}</td>
                <td>
                  <form id="book_shift_form_{{ workshift.id }}" method="POST" action="{% url 'scheduling:book_workshift' %}">
                    {% csrf_token %}
                    <input type="hidden" name="workshift_id" value="{{ workshift.id }}">
                    <button type="submit" class="btn btn-primary btn-sm">
                      <i class="fas fa-book"></i> Book Shift
                    </button>                
                  </form>
                </td>
              </tr>
            {% else %}
              <tr>
                <td colspan="6" class="text-center text-muted"><i class="fas fa-exclamation-triangle"></i> No upcoming shifts for this workshift.</td>
              </tr>
            {% endif %}
          {% empty %}
            <tr>
              <td colspan="6" class="text-center text-muted"><i class="fas fa-exclamation-triangle"></i> No available workshifts.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      <i class="fas fa-info-circle"></i> No available workshifts at the moment.
    </div>
  {% endif %}

  {% if error_message %}
    <div class="alert alert-danger" role="alert">
      <i class="fas fa-exclamation-circle"></i> {{ error_message }}
    </div>
  {% endif %}
</div>
{% endblock %}

scheduling/templates/scheduling/calendar.html
{% extends 'dashboard.html' %}

{% block content %}
  <h1>Book Workshift</h1>
  <h2>{{ workshift }}</h2>
  <p>Start Time: {{ workshift.start_time }}</p>
  <p>End Time: {{ workshift.end_time }}</p>
  <p>Role: {{ workshift.role }}</p>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Book Shift</button>
  </form>
{% endblock %}

scheduling/templates/scheduling/calendar2.html
{% extends 'dashboard.html' %}

{% block content %}
  <div class="container">
    <ul class="nav nav-tabs" id="viewTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="calendar-tab" data-toggle="tab" href="#calendar-view" role="tab" aria-controls="calendar-view" aria-selected="true">Calendar View</a>
      </li>
    </ul>
    <div class="tab-content" id="viewTabContent">
      <div class="tab-pane fade show active" id="calendar-view" role="tabpanel" aria-labelledby="calendar-tab">
        <div id="calendar"></div>
      </div>
      <div class="tab-pane fade" id="list-view" role="tabpanel" aria-labelledby="list-tab">
        {% if shifts %}
          <div class="list-group mt-3">
            {% for shift in shifts %}
              <a href="{% url 'scheduling:book_workshift' %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ shift.event }}</h5>
                  <small>{{ shift.start_time|date:"F d, Y" }}</small>
                </div>
                <p class="mb-1">Time: {{ shift.start_time|time:"H:i" }} - {{ shift.end_time|time:"H:i" }}</p>
              </a>
            {% endfor %}
          </div>
        {% else %}
          <p>No shifts available.</p>
        {% endif %}
      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.7/index.global.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
  
      var shifts = [
        {% for shift in shifts %}
          {% if shift.start_time > shift.get_current_time %}
            {
              title: '{{ shift.event }}',
              start: '{{ shift.start_time|date:"Y-m-d H:i:s" }}',
              end: '{{ shift.end_time|date:"Y-m-d H:i:s" }}',
              url: '{% url 'scheduling:book_workshift' %}'  // Update the URL here
            },
          {% endif %}
        {% endfor %}
      ];
  
      var calendar = new FullCalendar.Calendar(calendarEl, {
        themeSystem: 'bootstrap5',
        initialView: 'dayGridMonth',
        events: shifts,
        eventClick: function(info) {
          window.location.href = info.event.url;
        },
        eventTimeFormat: {
          hour: '2-digit',
          minute: '2-digit',
          hour12: false
        }
      });
  
      calendar.render();
    });
  </script>  
{% endblock %}

scheduling/templates/scheduling/cancel_workshift.html
{% extends 'dashboard.html' %}

{% block content %}
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Cancel Workshift</h1>
        <p class="card-text">Are you sure you want to cancel the workshift "{{ workshift.event }}"?</p>
        <form method="post" action="{% url 'scheduling:cancel_workshift' workshift_id=workshift.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Cancel Workshift</button>
        </form>
      </div>
    </div>
  </div>
  <hr>
{% endblock %}

scheduling/templates/scheduling/email_template.html
<h1>Workshift Booking Confirmation</h1>
<p>You have successfully booked the following workshift:</p>
<ul>
    <li>Event: {{ workshift.event }}</li>
    <li>Location: {{ workshift.location }}</li>
    <li>Start Time: {{ workshift.start_time|date:'H:i' }}</li>
    <li>End Time: {{ workshift.end_time|date:'H:i' }}</li>
    <li>Role: {{ workshift.role }}</li>
</ul>

scheduling/templates/scheduling/employees_calendar.html
{% extends 'dashboard.html' %}

{% block content %}
  <div class="container">
    <ul class="nav nav-tabs" id="viewTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="calendar-tab" data-toggle="tab" href="#calendar-view" role="tab" aria-controls="calendar-view" aria-selected="true">Calendar View</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="list-tab" data-toggle="tab" href="#list-view" role="tab" aria-controls="list-view" aria-selected="false">List View</a>
      </li>
    </ul>
    <div class="tab-content" id="viewTabContent">
      <div class="tab-pane fade show active" id="calendar-view" role="tabpanel" aria-labelledby="calendar-tab">
        <div id="calendar"></div>
      </div>
      <div class="tab-pane fade" id="list-view" role="tabpanel" aria-labelledby="list-tab">
        {% if shifts %}
          <div class="list-group mt-3">
            {% for shift in shifts %}
              <a href="{% url 'scheduling:book_workshift' %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ shift.name }}</h5>
                  <small>{{ shift.start_time|date:"F d, Y" }}</small>
                </div>
                <p class="mb-1">Time: {{ shift.start_time|time:"H:i" }} - {{ shift.end_time|time:"H:i" }}</p>
                <p class="mb-1">Booked Users: 
                  {% for booking in shift.bookings.all %}
                    {{ booking.user.username }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </p>
              </a>
            {% endfor %}
          </div>
        {% else %}
          <p>No shifts available.</p>
        {% endif %}
      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.7/index.global.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
  
      var shifts = [
        {% for shift in all_shifts %}
          {
            title: '{{ shift.name }}',
              start: '{{ shift.start_time|date:"Y-m-d H:i:s" }}',
              end: '{{ shift.end_time|date:"Y-m-d H:i:s" }}',
            url: '{% url 'scheduling:book_workshift' %}',  // Update the URL here
            description: 'Booked Users: {% for booking in shift.bookings.all %}{{ booking.user.username }}{% if not forloop.last %}, {% endif %}{% endfor %}'
          }{% if not forloop.last %},{% endif %}
        {% endfor %}
      ];
  
      var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        events: shifts,
        eventClick: function(info) {
          window.location.href = info.event.url;
        },
        eventTimeFormat: {
          hour: '2-digit',
          minute: '2-digit',
          hour12: false
        },
        eventDidMount: function(info) {
          $(info.el).tooltip({
            title: info.event.extendedProps.description,
            placement: 'top',
            trigger: 'hover',
            container: 'body'
          });
        }
      });
  
      calendar.render();
    });
</script>


{% endblock %}

scheduling/templates/scheduling/work_shifts.html
{% extends 'dashboard.html' %}

{% block content %}
  <div class="container">
    <h1 class="text-center my-4">My Workshifts</h1>
    
    <section>
      <h2 class="mb-4">Booked Workshifts</h2>
      {% if booked_workshifts %}
        <div class="list-group">
          {% for workshift in booked_workshifts %}
            <div class="list-group-item list-group-item-action">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ workshift.event }}</h5>
                <small>Date: {{ workshift.start_time|date:"F d, Y" }}</small>
              </div>
              <p class="mb-1">Time: {{ workshift.start_time|time:"H:i" }} - {{ workshift.end_time|time:"H:i" }}</p>
              {% if workshift.start_time > workshift.get_current_time %}
                <a href="{% url 'scheduling:cancel_workshift' workshift_id=workshift.id %}" class="btn btn-danger btn-sm"><i class="fas fa-times"></i> Cancel Workshift</a>
              {% else %}
                <p>This workshift has already passed and cannot be canceled.</p>
                <small>Current Time: {{ workshift.get_current_time }}</small>
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p>No booked workshifts.</p>
      {% endif %}
    </section>

    <hr>

    <section>
      <h2 class="my-4">Worked Workshifts</h2>
      {% if worked_workshifts %}
        <div class="list-group">
          {% for workshift in worked_workshifts %}
            <div class="list-group-item list-group-item-action">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ workshift.event }}</h5>
                <small>Date: {{ workshift.start_time|date:"F d, Y" }}</small>
              </div>
              <p class="mb-1">Time: {{ workshift.start_time|time:"H:i" }} - {{ workshift.end_time|time:"H:i" }}</p>
              <p>This workshift has already passed and cannot be canceled.</p>
              <small>Current Status: Worked</small>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p>No worked workshifts.</p>
      {% endif %}
    </section>
  </div>
  <br>
{% endblock %}

scheduling/templates/scheduling/workshift_detail.html
{% extends 'dashboard.html' %}

{% block content %}
  <h1>Book Workshift</h1>
  <h2>{{ workshift }}</h2>
  <p>Start Time: {{ workshift.start_time }}</p>
  <p>End Time: {{ workshift.end_time }}</p>
  <p>Role: {{ workshift.role }}</p>
  
  <form method="POST" action="{% url 'scheduling:book_workshift' workshift_id=workshift.id %}">
    {% csrf_token %}
    <!-- Include any form fields you need for the booking -->
    <button type="submit" class="btn btn-primary">Book Shift</button>
  </form>
{% endblock %}

scheduling/templates/scheduling/workshift_list.html
{% extends 'dashboard.html' %}

{% block content %}
  <div class="container">
    <h2>Workshift List</h2>
    {% if cancel_requests %}
      <h3>Cancelation Requests</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Event</th>
            <th>Location</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for workshift in cancel_requests %}
            <tr>
              <td>{{ workshift.event }}</td>
              <td>{{ workshift.location }}</td>
              <td>{{ workshift.start_time }}</td>
              <td>{{ workshift.end_time }}</td>
              <td>
                <form method="POST" action="{% url 'scheduling:approve_cancelation' workshift.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-check"></i> Approve</button>
                </form>
                <form method="POST" action="{% url 'scheduling:reject_cancelation' workshift.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-times"></i> Reject</button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h3>No cancelation requests.</h3>
    {% endif %}

    {% if workshifts %}
      <h3>Available Workshifts</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Event</th>
            <th>Location</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for workshift in workshifts %}
            <tr>
              <td>{{ workshift.event }}</td>
              <td>{{ workshift.location }}</td>
              <td>{{ workshift.start_time }}</td>
              <td>{{ workshift.end_time }}</td>
              <td>
                <form method="POST" action="{% url 'scheduling:book_workshift' %}">
                  {% csrf_token %}
                  <input type="hidden" name="workshift_id" value="{{ workshift.id }}">
                  <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-calendar-plus"></i> Book</button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h3>No available workshifts.</h3>
    {% endif %}
  </div>
{% endblock %}