authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('login2/', views.user_login2, name='login2'),
    path('logout/', views.user_logout, name='logout'),
]

hr_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from news.views import news_feed
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('booking/', include('booking.urls')),
    path('profiles/', include('profiles.urls')),
    path('scheduling/', include('scheduling.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('contact/', TemplateView.as_view(template_name="contact.html"), name="contact"),
    path('services/', TemplateView.as_view(template_name="services.html"), name="services"),
    path('aboutus/', TemplateView.as_view(template_name="aboutus.html"), name="aboutus"),
    path('news/', include('news.urls', namespace='news')),
    path('summernote/', include('django_summernote.urls')),
    path('login/', LoginView.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import news_feed, like_post, add_comment

app_name = 'news'

urlpatterns = [
    path('', news_feed, name='news_feed'),
    path('like/<int:post_id>/', like_post, name='like_post'),
    path('comment/<int:post_id>/', add_comment, name='add_comment'),
]

profiles/urls.py
from django.urls import path
from . import views
from .views import links, knowledge_base

app_name = 'profiles'

urlpatterns = [
    path('detail/', views.profile_detail, name='profile_detail'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('work_shifts/', views.work_shifts, name='work_shifts'),
    path('links/', links, name='links'),
    path('employees/', views.employees, name='employees'),
    path('detail/<int:user_id>/', views.profile_detail, name='profile_detail'),
    path('admin/employee_profiles/', views.admin_view_profiles, name='admin_view_profiles'),
    path('knowledgebase/', knowledge_base, name='knowledgebase'),
]

scheduling/urls.py
from django.urls import path
from . import views
from booking.views import book_pass

app_name = 'scheduling'

urlpatterns = [
    path('list/', views.workshift_list, name='workshift_list'),
    path('book/', views.book_workshift, name='book_workshift'),
    path('book/<int:workshift_id>/', views.book_workshift, name='book_workshift'),
    path('book-pass/<int:workshift_id>/', book_pass, name='book_pass'),
    path('work-shifts/', views.work_shifts, name='work_shifts'),
    path('work-shifts/add-event/', views.add_event, name='add_event'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('calendar2/', views.calendar_view, name='calendar2'),
    path('employees_calendar/', views.employees_calendar_view, name='employees_calendar'),
    path('cancel/<int:workshift_id>/', views.cancel_workshift, name='cancel_workshift'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HR System - </title>

  <!-- Custom fonts for this template-->
  <link rel="stylesheet" href="{% static 'css/all_style.css' %}">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link rel="stylesheet" href="{% static 'css/admin_style.css' %}">
  <script src="{% static 'js/email.js' %}"></script>
  <script src="https://cdn.emailjs.net/sdk/2.6.4/email.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.8.0/main.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.8.0/main.min.js"></script>
  <script src="https://kit.fontawesome.com/1f28a44c72.js" crossorigin="anonymous"></script>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center"
        href="{% url 'profiles:profile_detail' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-user-friends"></i>
        </div>
        <div class="sidebar-brand-text mx-3">HR System <sup>v2.0</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Heading -->
      <div class="sidebar-heading">
        Menu
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profiles:profile_detail' %}">
          <i class="fas fa-fw fa-user"></i>
          <span>Profile</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'scheduling:work_shifts' %}">
          <i class="fas fa-fw fa-calendar"></i>
          <span>My Schedule</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'scheduling:book_workshift' %}">
          <i class="fas fa-fw fa-calendar-plus"></i>
          <span>Book Shifts</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'scheduling:calendar' %}">
          <i class="far fa-fw fa-calendar-alt"></i>
          <span>Calendar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'news:news_feed' %}">
          <i class="fas fa-fw fa-newspaper"></i>
          <span>News</span>
        </a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider">
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">
          <i class="fas fa-fw fa-user-shield"></i>
          <span>Adminpanel</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profiles:links' %}">
          <i class="fas fa-fw fa-link"></i>
          <span>Links</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profiles:employees' %}">
          <i class="fas fa-fw fa-users"></i>
          <span>Employees</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'scheduling:employees_calendar' %}">
          <i class="far fa-fw fa-calendar-alt"></i>
          <span>Employees Calendar</span>
        </a>
      </li>
      {% endif %}
      <!-- Divider -->
      <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:logout' %}">
          <i class="fas fa-fw fa-sign-out-alt"></i>
          <span>Logout</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">
          <i class="fas fa-fw fa-home"></i>
          <span>Back to Home</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:register' %}">
          <i class="fas fa-fw fa-user-plus"></i>
          <span>Register</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:login' %}">
          <i class="fas fa-fw fa-sign-in-alt"></i>
          <span>Login</span>
        </a>
      </li>
      {% endif %}
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>


          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                {% if user.is_authenticated %}
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">You are logged in as:
                  {{ profile.user.first_name }} {{ profile.user.last_name }}</span>
                <img class="img-profile rounded-circle" src="{% static 'profile_image.jpeg' %}">
                {% endif %}
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'profiles:profile_detail' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="{% url 'profiles:edit_profile' %}">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Edit Profile
                </a>
                <a class="dropdown-item" href="{% url 'news:news_feed' %}">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  News
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'authentication:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <main class="container">
          {% block content %}
          {% endblock %}
        </main>

        <footer>
          <footer class="sticky-footer bg-white">
            <div class="container my-auto">
              <div class="copyright text-center my-auto">
                <span>
                  <p> HR Mangament, Created with <span class="heart">❤️</span> by <a href="https://github.com/bjorne90"
                      target="_blank">Björn Centio 2023</a></p>
                </span>
              </div>
            </div>
          </footer>
        </footer>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/admin.js' %}"></script>
</body>

</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>HR Management | Dashboard</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'logo_2.png' %}" rel="icon">
  <link href="{% static 'logo_2.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- CDN CSS Files -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
  <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.8.0/main.min.js"></script>

</head>

<body>

  <!-- Header -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'profiles:profile_detail' %}" class="logo d-flex align-items-center">
        <img src="{% static 'logo_2.png' %}" alt="">
        <span class="d-none d-lg-block">HR Mangament</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div>
    <!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {% if user.is_authenticated %}
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">You are logged in as:
              {{ user.first_name }} {{ user.last_name }}</span>
            <img class="img-profile rounded-circle" src="{% static 'profile_image.jpeg' %}">
            {% endif %}
          </a>
          <!-- Dropdown - User Information -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="{% url 'profiles:profile_detail' %}">
              <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
              Profile
            </a>
            <a class="dropdown-item" href="{% url 'profiles:edit_profile' %}">
              <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
              Edit Profile
            </a>
            <a class="dropdown-item" href="{% url 'news:news_feed' %}">
              <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
              News
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'authentication:logout' %}">
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              Logout
            </a>
          </div>
        </li>

      </ul>
    </nav>
    <!-- End Icons Navigation -->

  </header>
  <!-- End Header -->

  <!-- Sidebar -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-heading">Pages</li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profiles:profile_detail' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li>
      <!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'scheduling:work_shifts' %}">
          <i class="bi bi-calendar"></i>
          <span>My Schedule</span>
        </a>
      </li>
      <!-- End My Schedule Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'scheduling:book_workshift' %}">
          <i class="bi bi-bookmark-plus"></i>
          <span>Book Shift</span>
        </a>
      </li><!-- End Contact Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'scheduling:calendar' %}">
          <i class="bi bi-calendar-week"></i>
          <span>Calendar</span>
        </a>
      </li>
      <!-- End Book Shif Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'news:news_feed' %}">
          <i class="bi bi-newspaper"></i>
          <span>News</span>
        </a>
      </li>
      <!-- End News Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profiles:links' %}">
          <i class="bi bi-box-arrow-up-right"></i>
          <span>Links</span>
        </a>
      </li>
      <!-- End Links Page Nav -->

      <!-- Divider -->
      <hr class="sidebar-divider">
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'admin:index' %}" target="_blank">
          <i class="bi bi-file-earmark-lock-fill"></i>
          <span>Admin</span>
        </a>
      </li>
      <!-- End Admin Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profiles:knowledgebase' %}">
          <i class="bi bi-file-earmark-word"></i>
          <span>Knowledge base</span>
        </a>
      </li>
      <!-- End Knowledge base Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profiles:employees' %}">
          <i class="bi bi-people"></i>
          <span>Employees</span>
        </a>
      </li>
      <!-- End Employees Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'scheduling:employees_calendar' %}">
          <i class="bi bi-calendar3"></i>
          <span>Employees Calendar</span>
        </a>
      </li>
      <!-- End Employees Calendar Page Nav -->
      {% endif %}
      <!-- Divider -->
      <hr class="sidebar-divider">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'authentication:logout' %}">
          <i class="bi bi-box-arrow-left"></i>
          <span>Logout</span>
        </a>
      </li>
      <!-- End Logout Nav -->
      {% else %}

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'home' %}">
          <i class="bi bi-house-door"></i>
          <span>Home</span>
        </a>
      </li>
      <!-- End Home Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'authentication:register' %}">
          <i class="bi bi-check-circle"></i>
          <span>Register</span>
        </a>
      </li>
      <!-- End Register Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'authentication:login' %}">
          <i class="bi bi-box-arrow-right"></i>
          <span>Login</span>
        </a>
      </li>
      <!-- End Login Page Nav -->
      {% endif %}

    </ul>

  </aside>
  <!-- End Sidebar-->

  <main id="main" class="main">
    {% block content %}
    {% endblock %}
  </main>
  <!-- End main block -->



  <!-- Footer -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>HR Mangament</span></strong> 2023. All Rights Reserved
    </div>
    <div class="credits">
      Created with <span class="heart">❤️</span> by <a href="https://github.com/bjorne90" target="_blank">Björn
        Centio</a>
    </div>
  </footer>
  <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- CDN JS Files -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.40.0/apexcharts.min.js"
    integrity="sha512-Kr1p/vGF2i84dZQTkoYZ2do8xHRaiqIa7ysnDugwoOcG0SbIx98erNekP/qms/hBDiBxj336//77d0dv53Jmew=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.3.0/chart.umd.js"
    integrity="sha512-CMF3tQtjOoOJoOKlsS7/2loJlkyctwzSoDK/S40iAB+MqWSaf50uObGQSk5Ny/gfRhRCjNLvoxuCvdnERU4WGg=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.2/echarts.min.js"
    integrity="sha512-VdqgeoWrVJcsDXFlQEKqE5MyhaIgB9yXUVaiUa8DR2J4Lr1uWcFm+ZH/YnzV5WqgKf4GPyHQ64vVLgzqGIchyw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.7/quill.min.js"
    integrity="sha512-P2W2rr8ikUPfa31PLBo5bcBQrsa+TNj8jiKadtaIrHQGMo6hQM6RdPjQYxlNguwHz8AwSQ28VkBK6kHBLgd/8g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.4.2/tinymce.min.js"
    integrity="sha512-sWydClczl0KPyMWlARx1JaxJo2upoMYb9oh5IHwudGfICJ/8qaCyqhNTP5aa9Xx0aCRBwh71eZchgz0a4unoyQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://kit.fontawesome.com/1f28a44c72.js" crossorigin="anonymous"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/demo.js' %}"></script>
  <script src="{% static 'js/admin.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  
  <!-- Plugin JavaScript-->
  <script src="{% static 'js/jquery.easing.min.js' %}"></script>

</body>

</html>

templates/employees.html
{% extends 'demo_dashboard.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h1 class="text-center text-primary mb-4"><i class="fas fa-users"></i> Employee List</h1>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th><i class="fas fa-user"></i> First Name</th>
                    <th><i class="fas fa-user"></i> Last Name</th>
                    <th><i class="fas fa-envelope"></i> Email</th>
                    <th><i class="fas fa-briefcase"></i> Work Title</th>
                    <th><i class="fas fa-id-badge"></i> Work ID</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.profile.work_title }}</td>
                        <td>{{ user.profile.work_id }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Bootstrap Pagination -->
    <nav aria-label="Page navigation example" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-chevron-left"></i> Previous</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link"><i class="fas fa-chevron-left"></i> Previous</span></li>
            {% endif %}
        
            {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                    <li class="page-item active"><span class="page-link">{{ page }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next <i class="fas fa-chevron-right"></i></a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">Next <i class="fas fa-chevron-right"></i></span></li>
            {% endif %}
        </ul>
    </nav>
</div>
<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/1f28a44c72.js" crossorigin="anonymous"></script>
{% endblock %}

templates/news_feed.html
{% extends 'dashboard.html' %}
{% load static %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-5 text-center text-primary">News Feed</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {% for news_item in news_items %}
        <div class="col">
          <div class="card h-100 border-primary shadow">
            <img src="{{ news_item.image.url }}" class="card-img-top smaller-image" alt="News Image">
            <div class="card-body">
              <h3 class="card-title">{{ news_item.title }}</h3>
              <p class="card-text">{{ news_item.content }}</p>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center bg-white">
              <small class="text-muted">Published on: {{ news_item.timestamp }}</small>
              <div>
                <form action="{% url 'news:like_post' news_item.id %}" method="post" class="d-inline">
                  {% csrf_token %}
                  {% if request.user in news_item.likes.all %}
                    <button type="submit" class="btn btn-sm btn-primary">
                      <i class="fas fa-thumbs-down"></i> Unlike
                    </button>
                  {% else %}
                    <button type="submit" class="btn btn-sm btn-outline-primary">
                      <i class="fas fa-thumbs-up"></i> Like
                    </button>
                  {% endif %}
                </form>                
                <small class="text-muted"><i class="fas fa-heart"></i> {{ news_item.likes.count }}</small>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <div class="col">
          <p class="text-center">No news items available.</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}